from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='OfficeProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name',models.CharField(default='دفتر املاک',max_length=160)),('phone',models.CharField(blank=True,max_length=30)),('mobile',models.CharField(blank=True,max_length=30)),('address',models.CharField(blank=True,max_length=300)),('city',models.CharField(blank=True,max_length=80)),('description',models.TextField(blank=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Agent', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('role',models.CharField(blank=True,max_length=120)),('phone',models.CharField(max_length=30)),('bio',models.TextField(blank=True)),('image',models.ImageField(blank=True,null=True,upload_to='agents/')),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Property', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=220)),('slug',models.SlugField(blank=True, unique=True)),('deal_type',models.CharField(choices=[('sale','فروش'),('rent','اجاره'),('mortgage','رهن')],max_length=20)),('property_type',models.CharField(choices=[('apartment','آپارتمان'),('house','خانه'),('villa','ویلا'),('land','زمین'),('commercial','تجاری')],max_length=20)),('city',models.CharField(max_length=80)),('district',models.CharField(max_length=120)),('address',models.CharField(blank=True,max_length=300)),('area',models.PositiveIntegerField()),('bedrooms',models.PositiveSmallIntegerField(default=0)),('floor',models.CharField(blank=True,max_length=20)),('built_year',models.PositiveSmallIntegerField(blank=True,null=True)),('price',models.DecimalField(decimal_places=0,default=0,max_digits=18)),('deposit',models.DecimalField(decimal_places=0,default=0,max_digits=18)),('rent',models.DecimalField(decimal_places=0,default=0,max_digits=18)),('description',models.TextField(blank=True)),('parking',models.BooleanField(default=False)),('elevator',models.BooleanField(default=False)),('storage',models.BooleanField(default=False)),('balcony',models.BooleanField(default=False)),('featured',models.BooleanField(default=False)),('status',models.CharField(choices=[('available','موجود'),('negotiating','در مذاکره'),('sold','فروخته شد'),('rented','اجاره رفت')],default='available',max_length=20)),('image',models.ImageField(blank=True,null=True,upload_to='properties/')),('agent',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='properties',to='core.agent')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='PropertyImage', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(upload_to='properties/gallery/')),('caption',models.CharField(blank=True,max_length=180)),('sort_order',models.PositiveSmallIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('property',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='gallery',to='core.property'))]),
        migrations.CreateModel(name='Lead', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('phone',models.CharField(max_length=30)),('message',models.TextField(blank=True)),('preferred_time',models.CharField(blank=True,max_length=100)),('status',models.CharField(choices=[('new','جدید'),('contacted','تماس گرفته شد'),('visit','بازدید'),('closed','معامله شد'),('cancelled','لغو شد')],default='new',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('property',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='leads',to='core.property'))]),
    ]
