from django.db import migrations,models
class Migration(migrations.Migration):
    dependencies=[('core','0004_lead_crm')]
    operations=[migrations.CreateModel(name='SiteSettings',fields=[
        ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('site_name',models.CharField(default='املاک پرو',max_length=120)),('site_tagline',models.CharField(default='خانه‌ای که دنبالش هستید، پیدا می‌کنیم.',max_length=220)),('logo',models.ImageField(blank=True,null=True,upload_to='site/')),('hero_image',models.ImageField(blank=True,null=True,upload_to='site/')),
        ('primary_color',models.CharField(default='#b8945c',max_length=7)),('secondary_color',models.CharField(default='#11110f',max_length=7)),('background_color',models.CharField(default='#f5f3ee',max_length=7)),('text_color',models.CharField(default='#171714',max_length=7)),('accent_color',models.CharField(default='#c6a66e',max_length=7)),('line_color',models.CharField(default='#dedbd3',max_length=7)),
        ('nav_home',models.CharField(default='خانه',max_length=60)),('nav_properties',models.CharField(default='املاک',max_length=60)),('nav_agents',models.CharField(default='مشاوران',max_length=60)),('nav_about',models.CharField(default='درباره ما',max_length=60)),('nav_contact',models.CharField(default='تماس با ما',max_length=60)),('nav_favorites',models.CharField(default='علاقه‌مندی‌ها',max_length=60)),
        ('hero_eyebrow',models.CharField(default='دفتر تخصصی خرید، فروش و اجاره',max_length=160)),('hero_title',models.CharField(default='ملک مناسب شما،',max_length=220)),('hero_title_emphasis',models.CharField(default='همین‌جاست.',max_length=120)),('hero_description',models.TextField(default='با جست‌وجوی دقیق و مشاوره حرفه‌ای، انتخاب بعدی‌تان را مطمئن‌تر کنید.')),('hero_search_label',models.CharField(default='جست‌وجو',max_length=80)),('hero_search_placeholder',models.CharField(default='مثلاً سعادت‌آباد، آپارتمان ۱۲۰ متری',max_length=180)),('hero_deal_label',models.CharField(default='نوع معامله',max_length=80)),('hero_search_button',models.CharField(default='جست‌وجوی ملک',max_length=100)),
        ('featured_eyebrow',models.CharField(default='انتخاب‌های ویژه',max_length=100)),('featured_title',models.CharField(default='ملک‌هایی که ارزش دیدن دارند',max_length=180)),('featured_link',models.CharField(default='مشاهده همه ←',max_length=100)),('empty_properties_text',models.CharField(default='هنوز ملک ویژه‌ای ثبت نشده؛ از پنل مدیریت اضافه کنید.',max_length=180)),
        ('trust_1_title',models.CharField(default='مشاوره شفاف',max_length=100)),('trust_1_text',models.CharField(default='اطلاعات روشن و قابل بررسی برای تصمیمی بهتر.',max_length=220)),('trust_2_title',models.CharField(default='انتخاب دقیق',max_length=100)),('trust_2_text',models.CharField(default='فیلترهای کاربردی برای رسیدن سریع‌تر به گزینه مناسب.',max_length=220)),('trust_3_title',models.CharField(default='همراه تا معامله',max_length=100)),('trust_3_text',models.CharField(default='از اولین تماس تا بازدید و نهایی‌شدن معامله.',max_length=220)),
        ('about_eyebrow',models.CharField(default='شناخت بیشتر',max_length=100)),('about_title',models.CharField(default='درباره املاک پرو',max_length=180)),('about_intro',models.TextField(default='یک دفتر املاک مدرن برای پیدا کردن، مقایسه و انتخاب مطمئن‌تر ملک.')),('about_card_1_title',models.CharField(default='انتخاب ملک، ساده و شفاف',max_length=120)),('about_card_1_text',models.TextField(default='در املاک پرو تلاش می‌کنیم اطلاعات ملک‌ها را روشن و کاربردی ارائه کنیم تا مسیر جست‌وجو تا معامله برای شما ساده‌تر باشد.')),('about_card_2_title',models.CharField(default='مشاوره تخصصی',max_length=120)),('about_card_2_text',models.TextField(default='برای خرید، فروش، رهن و اجاره می‌توانید با مشاوران مجموعه در ارتباط باشید و قبل از تصمیم نهایی اطلاعات لازم را دریافت کنید.')),('about_card_3_title',models.CharField(default='همراه تا معامله',max_length=120)),('about_card_3_text',models.TextField(default='هدف ما فقط نمایش یک ملک نیست؛ می‌خواهیم از اولین جست‌وجو تا بازدید و نهایی‌شدن معامله، تجربه‌ای منظم و قابل اعتماد داشته باشید.')),
        ('contact_eyebrow',models.CharField(default='در ارتباط باشیم',max_length=100)),('contact_title',models.CharField(default='تماس با ما',max_length=120)),('contact_intro',models.TextField(default='برای پرسش درباره ملک‌ها، هماهنگی بازدید یا دریافت مشاوره با دفتر املاک پرو در ارتباط باشید.')),('contact_phone_label',models.CharField(default='تلفن دفتر',max_length=80)),('contact_mobile_label',models.CharField(default='موبایل',max_length=80)),('contact_address_label',models.CharField(default='آدرس دفتر',max_length=80)),('contact_cta_eyebrow',models.CharField(default='نیاز به پیدا کردن ملک دارید؟',max_length=120)),('contact_cta_title',models.CharField(default='از بین ملک‌های موجود شروع کنید.',max_length=180)),('contact_cta_button',models.CharField(default='مشاهده املاک',max_length=100)),('footer_copyright',models.CharField(default='© ۱۴۰۵ — تمامی حقوق محفوظ است.',max_length=180)),('instagram_url',models.URLField(blank=True)),('telegram_url',models.URLField(blank=True)),('updated_at',models.DateTimeField(auto_now=True))
    ],options={'verbose_name':'تنظیمات ظاهری سایت','verbose_name_plural':'تنظیمات ظاهری سایت'})]