from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies=[('core','0007_contact_labels')]
    operations=[
        migrations.AddField(model_name='officeprofile',name='name_en',field=models.CharField(default='Real Estate Office',max_length=160)),
        migrations.AddField(model_name='officeprofile',name='city_en',field=models.CharField(blank=True,max_length=80)),
        migrations.AddField(model_name='officeprofile',name='address_en',field=models.CharField(blank=True,max_length=300)),
        migrations.AddField(model_name='officeprofile',name='description_en',field=models.TextField(blank=True)),
        migrations.AddField(model_name='agent',name='name_en',field=models.CharField(blank=True,max_length=120)),
        migrations.AddField(model_name='agent',name='role_en',field=models.CharField(blank=True,max_length=120)),
        migrations.AddField(model_name='agent',name='bio_en',field=models.TextField(blank=True)),
        migrations.AddField(model_name='property',name='title_en',field=models.CharField(blank=True,max_length=220)),
        migrations.AddField(model_name='property',name='city_en',field=models.CharField(blank=True,max_length=80)),
        migrations.AddField(model_name='property',name='district_en',field=models.CharField(blank=True,max_length=120)),
        migrations.AddField(model_name='property',name='address_en',field=models.CharField(blank=True,max_length=300)),
        migrations.AddField(model_name='property',name='description_en',field=models.TextField(blank=True)),
        migrations.AddField(model_name='sitesettings',name='site_name_en',field=models.CharField(default="AmlakPro",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='site_tagline_en',field=models.CharField(default="We help you find the home you're looking for.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='nav_home_en',field=models.CharField(default="Home",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='nav_properties_en',field=models.CharField(default="Properties",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='nav_agents_en',field=models.CharField(default="Agents",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='nav_about_en',field=models.CharField(default="About Us",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='nav_contact_en',field=models.CharField(default="Contact Us",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='nav_favorites_en',field=models.CharField(default="Favorites",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_eyebrow_en',field=models.CharField(default="Specialized buying, selling and rental office",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_title_en',field=models.CharField(default="The right property for you,",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_title_emphasis_en',field=models.CharField(default="is right here.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_description_en',field=models.TextField(default="With precise search and professional advice, make your next property decision with confidence.")),
        migrations.AddField(model_name='sitesettings',name='hero_search_label_en',field=models.CharField(default="Search",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_search_placeholder_en',field=models.CharField(default="e.g. Saadat Abad, 120 m² apartment",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_deal_label_en',field=models.CharField(default="Deal type",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='hero_search_button_en',field=models.CharField(default="Search properties",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='featured_eyebrow_en',field=models.CharField(default="Featured picks",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='featured_title_en',field=models.CharField(default="Properties worth seeing",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='featured_link_en',field=models.CharField(default="View all →",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='empty_properties_text_en',field=models.CharField(default="No featured property has been added yet.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='trust_1_title_en',field=models.CharField(default="Transparent advice",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='trust_1_text_en',field=models.CharField(default="Clear, verifiable information for better decisions.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='trust_2_title_en',field=models.CharField(default="Precise selection",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='trust_2_text_en',field=models.CharField(default="Useful filters to reach the right option faster.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='trust_3_title_en',field=models.CharField(default="With you to the deal",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='trust_3_text_en',field=models.CharField(default="From the first call to viewing and closing.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_eyebrow_en',field=models.CharField(default="Learn more",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_title_en',field=models.CharField(default="About AmlakPro",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_intro_en',field=models.TextField(default="A modern real estate office for finding, comparing and choosing property with confidence.")),
        migrations.AddField(model_name='sitesettings',name='about_card_1_title_en',field=models.CharField(default="Simple and transparent",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_card_1_text_en',field=models.TextField(default="We present property information clearly and practically so your path from search to deal is easier.")),
        migrations.AddField(model_name='sitesettings',name='about_card_2_title_en',field=models.CharField(default="Expert advice",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_card_2_text_en',field=models.TextField(default="For buying, selling, mortgage and rental, our advisors are available to provide the information you need.")),
        migrations.AddField(model_name='sitesettings',name='about_card_3_title_en',field=models.CharField(default="With you to the deal",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_card_3_text_en',field=models.TextField(default="Our goal is more than displaying a property; we support you from the first search to the final deal.")),
        migrations.AddField(model_name='sitesettings',name='properties_eyebrow_en',field=models.CharField(default="Properties",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_title_en',field=models.CharField(default="Your next property",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_intro_en',field=models.TextField(default="Search and filter the office's available properties.")),
        migrations.AddField(model_name='sitesettings',name='properties_search_placeholder_en',field=models.CharField(default="City, district or property name",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_deal_label_en',field=models.CharField(default="Deal type",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_type_label_en',field=models.CharField(default="Property type",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_ordering_label_en',field=models.CharField(default="Sort by",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_apply_button_en',field=models.CharField(default="Apply filters",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_clear_button_en',field=models.CharField(default="Clear",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_prev_button_en',field=models.CharField(default="Previous",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_next_button_en',field=models.CharField(default="Next",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_loading_text_en',field=models.CharField(default="Loading properties...",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_error_text_en',field=models.CharField(default="Could not load properties.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_empty_text_en',field=models.CharField(default="No property matches your search.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='properties_count_label_en',field=models.CharField(default="properties",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='agents_eyebrow_en',field=models.CharField(default="Our team",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='agents_title_en',field=models.CharField(default="Advisors who are here for you",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='agents_intro_en',field=models.TextField(default="Local expertise, responsiveness and support through the deal.")),
        migrations.AddField(model_name='sitesettings',name='agents_empty_text_en',field=models.CharField(default="No advisors have been added yet.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='agents_phone_label_en',field=models.CharField(default="Contact advisor",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='about_button_en',field=models.CharField(default="View properties",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_eyebrow_en',field=models.CharField(default="Let's connect",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_title_en',field=models.CharField(default="Contact us",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_intro_en',field=models.TextField(default="For property questions, viewing appointments or advice, contact AmlakPro.")),
        migrations.AddField(model_name='sitesettings',name='contact_office_name_label_en',field=models.CharField(default="Office name",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_city_label_en',field=models.CharField(default="City",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_description_label_en',field=models.CharField(default="Office introduction",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_phone_label_en',field=models.CharField(default="Office phone",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_mobile_label_en',field=models.CharField(default="Mobile",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_address_label_en',field=models.CharField(default="Office address",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_cta_eyebrow_en',field=models.CharField(default="Looking for a property?",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_cta_title_en',field=models.CharField(default="Start with the available properties.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='contact_cta_button_en',field=models.CharField(default="View properties",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='footer_copyright_en',field=models.CharField(default="© 2026 — All rights reserved.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='footer_office_empty_text_en',field=models.CharField(default="Office information is being completed.",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='instagram_label_en',field=models.CharField(default="Instagram",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='telegram_label_en',field=models.CharField(default="Telegram",max_length=220)),
        migrations.AddField(model_name='sitesettings',name='whatsapp_label_en',field=models.CharField(default="WhatsApp",max_length=220)),
    ]